language: haskell
before_install:
  - wget $STACKAGE 
  - cabal update
  - cabal install cabal-install
  - cabal install happy alex gtk2hs-buildtools
matrix:
  include:
    - ghc: "7.8"
      env: STACKAGE=http://www.stackage.org/lts/cabal.config
