flags: {}
packages:
- halma
- halma-gui
- halma-telegram-bot
extra-deps:
- grid-7.8.7
- mvc-1.1.3
- megaparsec-5.1.2
- telegram-api-0.5.1.2
- servant-0.9.1.1
- servant-client-0.9.1.1
- http-api-data-0.3.3
- http-client-0.5.4
- http-client-tls-0.3.3
- aeson-1.0.2.1
resolver: lts-6.27
